import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Proza_Libre } from "next/font/google";
import "./globals.css";
import Provider from "@/provider/Provider";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const inter = Proza_Libre({ subsets: ["latin"], weight: "400" });

// const minecraftFont = localFont({
//   src: "./fonts/minecraft_font.ttf",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} h-screen bg-background tracking-tight antialiased`}>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
